'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type Script = { id: string; thumbnailPath?: string | null; name: string; description: string; author: string; size: number; downloads: number; passwordProtected: boolean; createdAt: string };
const fmtSize = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(2)} MB`;
const fmtDate = (date: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date));
export default function HomePage() {
  const [scripts, setScripts] = useState<Script[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function refresh() { setLoading(true); setError(''); try { const res = await fetch('/api/scripts', { cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Gagal memuat daftar script.'); setScripts(data.scripts || []); } catch (e) { setError(e instanceof Error ? e.message : 'Gagal memuat data.'); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  const filtered = useMemo(() => scripts.filter(s => `${s.name} ${s.description} ${s.author}`.toLowerCase().includes(query.toLowerCase().trim())), [scripts, query]);
  const totalDownloads = scripts.reduce((n, s) => n + (s.downloads || 0), 0);
  return <main className="page-wrap"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> COMMUNITY SCRIPT LIBRARY <span className="eyebrow-num">001 / FX</span></div><h1>DROP YOUR<br/><span className="highlight">SCRIPT.</span><br/>SHARE THE <span className="outline-word">POWER.</span></h1><p className="hero-description">Tempat berbagi script bot dalam format ZIP. Upload karya kamu, temukan tools baru, dan bantu komunitas berkembang.</p><div className="hero-actions"><Link href="/publish" className="button button-primary">＋ UPLOAD SCRIPT <span>↗</span></Link><a href="#library" className="button button-white">JELAJAHI LIBRARY ↓</a></div><div className="hero-credit"><span className="avatar">K</span><span>BUILT BY <strong>KyZX</strong><small>MADE FOR THE COMMUNITY</small></span></div></div><div className="hero-art" aria-label="Ilustrasi FX Project"><div className="art-sticker sticker-top">ZIP IT<br/>SHIP IT.</div><div className="art-window"><div className="window-bar"><i/><i/><i/><span>fx_project.zip</span></div><div className="code-lines"><b>01</b><span className="line-long"/><b>02</b><span className="line-mid"/><b>03</b><span className="line-short"/><b>04</b><span className="line-long"/><b>05</b><span className="line-mid"/></div><div className="zip-badge">ZIP<span>↗</span></div></div><div className="art-sticker sticker-bottom">NO GATEKEEPING<br/><strong>JUST SHARING.</strong></div><div className="art-spark">✳</div><div className="art-plus">＋</div></div><div className="hero-side-label">FX / COMMUNITY / 2026</div></section>
  <section className="stats-grid" aria-label="Statistik"><div className="stat-card stat-blue"><span className="stat-icon">▤</span><span className="stat-label">SCRIPT TERUPLOAD</span><strong>{scripts.length.toLocaleString('id-ID')}</strong><small>FILE DI LIBRARY</small></div><div className="stat-card stat-yellow"><span className="stat-icon">⇩</span><span className="stat-label">TOTAL DOWNLOAD</span><strong>{totalDownloads.toLocaleString('id-ID')}</strong><small>DOWNLOAD TERHITUNG</small></div><div className="stat-card stat-pink"><span className="stat-icon">✳</span><span className="stat-label">OPEN COMMUNITY</span><strong>01<span className="stat-suffix"> / ALL</span></strong><small>SHARE YOUR WORK</small></div></section>
  <section className="library-section" id="library"><div className="section-heading"><div><div className="eyebrow dark-eyebrow">THE DROP ZONE <span className="eyebrow-num">{String(scripts.length).padStart(3, '0')} ITEMS</span></div><h2>THE <span className="underline-title">LIBRARY.</span></h2><p>Temukan script yang kamu butuhkan. Download, pelajari, kembangkan.</p></div><Link href="/publish" className="button button-dark">+ PUBLISH NEW</Link></div><div className="library-tools"><label className="search-box"><span>⌕</span><input aria-label="Cari script" value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari nama script, deskripsi, atau author..."/><kbd>SEARCH</kbd></label><span className="result-count">SHOWING <strong>{filtered.length}</strong> RESULTS</span></div>
  {loading ? <div className="state-card"><span className="loader"/><strong>MEMUAT LIBRARY...</strong><small>Sedang mengambil data script.</small></div> : error ? <div className="state-card error-state"><strong>OOPS, ADA MASALAH.</strong><p>{error}</p><button className="button button-dark" onClick={() => void refresh()}>COBA LAGI ↻</button></div> : filtered.length === 0 ? <div className="state-card"><div className="empty-icon">＋</div><strong>{query ? 'SCRIPT TIDAK DITEMUKAN.' : 'LIBRARY MASIH KOSONG.'}</strong><p>{query ? 'Coba kata kunci lain.' : 'Jadi orang pertama yang membagikan script di sini.'}</p>{!query && <Link href="/publish" className="button button-primary">UPLOAD SCRIPT ↗</Link>}</div> : <div className="script-grid">{filtered.map((script, index) => <article className="script-card" key={script.id}><div className={`card-top card-top-${index % 4}`}>{script.thumbnailPath && <img className="script-thumbnail" src={`/api/scripts/${script.id}/thumbnail`} alt={`Thumbnail ${script.name}`} loading="lazy" />}<span className="card-index">FX / {String(index + 1).padStart(3, '0')}</span><span className="zip-label">.ZIP</span><div className="file-illustration"><span>ZIP</span><i>↗</i></div>{script.passwordProtected && <span className="protected-tag">▣ PASSWORD</span>}</div><div className="script-card-body"><div className="script-meta"><span>{fmtDate(script.createdAt)}</span><span>{fmtSize(script.size)}</span></div><h3>{script.name}</h3><p>{script.description || 'Tidak ada deskripsi untuk script ini.'}</p><div className="script-card-footer"><span className="author-chip"><span className="author-avatar">{(script.author || '?').charAt(0).toUpperCase()}</span> {script.author}</span><span className="download-count">⇩ {script.downloads.toLocaleString('id-ID')}</span></div><Link href={`/scripts/${script.id}`} className="card-open">LIHAT SCRIPT <span>↗</span></Link></div></article>)}</div>}</section><section className="bottom-cta"><div><span className="eyebrow">YOUR TURN.</span><h2>GOT A SCRIPT?<br/><span>DROP IT HERE.</span></h2></div><Link href="/publish" className="button button-primary button-cta">UPLOAD YOUR ZIP <span>↗</span></Link><div className="cta-star">✳</div></section></main>
}
