'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
type Script = { id: string; thumbnailPath?: string | null; name: string; description: string; author: string; size: number; downloads: number; passwordProtected: boolean; createdAt: string };
const size = (n: number) => n < 1024 ? `${n} B` : n < 1048576 ? `${(n / 1024).toFixed(1)} KB` : `${(n / 1048576).toFixed(2)} MB`;
export default function ScriptDetail({ params }: { params: { id: string } }) {
  const [script, setScript] = useState<Script | null>(null); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(true); const [downloading, setDownloading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/scripts/${params.id}`, { cache: 'no-store' }).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Script tidak ditemukan.'); setScript(d.script); }).catch(e => setError(e instanceof Error ? e.message : 'Gagal memuat script.')).finally(() => setLoading(false)); }, [params.id]);
  async function download() { if (!script) return; setError(''); setDownloading(true); try { const res = await fetch(`/api/scripts/${script.id}/download`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); if (!res.ok) { const data = await res.json(); throw new Error(data.error || 'Download gagal.'); } const blob = await res.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${script.name.replace(/[\\/:*?"<>|]/g, '-').slice(0, 80) || 'script'}.zip`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); setScript({ ...script, downloads: script.downloads + 1 }); } catch (e) { setError(e instanceof Error ? e.message : 'Download gagal.'); } finally { setDownloading(false); } }
  if (loading) return <main className="page-wrap detail-page"><div className="state-card"><span className="loader"/><strong>MEMUAT SCRIPT...</strong></div></main>;
  if (!script) return <main className="page-wrap detail-page"><Link href="/" className="back-link">← KEMBALI KE LIBRARY</Link><div className="state-card error-state"><strong>SCRIPT TIDAK DITEMUKAN.</strong><p>{error}</p><Link href="/" className="button button-dark">KEMBALI</Link></div></main>;
  return <main className="page-wrap detail-page"><div className="breadcrumb"><Link href="/">← BACK TO LIBRARY</Link><span> / </span><strong>SCRIPT DETAILS</strong></div><section className="detail-layout"><div className="detail-art card-top card-top-0">{script.thumbnailPath && <img className="script-thumbnail detail-thumbnail" src={`/api/scripts/${script.id}/thumbnail`} alt={`Thumbnail ${script.name}`} />}<span className="card-index">FX / {script.id.slice(0, 6).toUpperCase()}</span><span className="zip-label">.ZIP</span><div className="detail-file-icon"><span>ZIP</span><i>↗</i></div><div className="detail-art-caption">COMMUNITY<br/>SCRIPT FILE</div></div><div className="detail-content"><div className="eyebrow dark-eyebrow">SCRIPT DETAILS <span className="eyebrow-num">FX / DOWNLOAD</span></div><h1>{script.name}<span className="title-period">.</span></h1><div className="detail-author"><span className="author-avatar large-avatar">{script.author.charAt(0).toUpperCase()}</span><span>UPLOADED BY<strong>{script.author}</strong></span></div><p className="detail-description">{script.description || 'Uploader tidak menambahkan deskripsi untuk script ini.'}</p><div className="detail-stats"><div><small>FILE SIZE</small><strong>{size(script.size)}</strong></div><div><small>DOWNLOADS</small><strong>{script.downloads.toLocaleString('id-ID')}</strong></div><div><small>ACCESS</small><strong>{script.passwordProtected ? 'LOCKED ▣' : 'PUBLIC ↗'}</strong></div></div>{script.passwordProtected && <label className="field-label detail-password">DOWNLOAD PASSWORD<input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Masukkan password" autoComplete="off" /></label>}{error && <div className="form-error">! {error}</div>}<button className="button button-primary full-button download-button" disabled={downloading} onClick={() => void download()}>{downloading ? <><span className="button-spinner"/> PREPARING ZIP...</> : <>⇩ DOWNLOAD SCRIPT <span>↗</span></>}</button><p className="form-disclaimer">Download dihitung setelah file berhasil disiapkan. Bagikan hanya file yang memang boleh kamu distribusikan.</p><Link href="/" className="back-link lower-back">← KEMBALI KE LIBRARY</Link></div></section></main>
}
